services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: ecodeli
      MYSQL_USER: ecodeliuser
      MYSQL_PASSWORD: ecodelipwd
      MYSQL_ROOT_PASSWORD: rootpwd
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    command: ["/bin/sh", "./wait-for-db.sh"]
    #volumes:
     # - ./api:/usr/src/app
      #- /usr/src/app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - db
    env_file:
      - ./api/.env

  frontoffice:
    image: nginx:alpine
    container_name: frontoffice
    volumes:
      - ./frontoffice:/usr/share/nginx/html
      - ./frontoffice/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "3000:80"
    restart: always

  backoffice:
    image: nginx:alpine
    container_name: backoffice
    volumes:
      - ./backoffice:/usr/share/nginx/html
    ports:
      - "3001:80"
    restart: always

volumes:
  db_data: